apiVersion: v1
kind: Secret
metadata:
  name: financial-secret
type: Opaque
stringData:
  openrouter-api-key: "sk-or-v1-xxx"
  news-api-key: "cef1-xxx"
  langfuse-public-key: "pk-lf-99-xx"
  langfuse-secret-key: "sk-lf-84c-xx"
  langfuse-base-url: "https://cloud.langfuse.com"
