apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: financial-keyvault
  namespace: financial
spec:
  provider: azure

  parameters:
    usePodIdentity: "false"
    clientID: "1a1907d5-4ab9-49e0-b329-827d491be98f"
    keyvaultName: "financial-key"
    tenantId: "3ad7ab73-4c91-4d09-a567-1e747a70c126"

    objects: |
      array:
        - |
          objectName: openrouter-api-key
          objectType: secret
        - |
          objectName: news-api-key
          objectType: secret
        - |
          objectName: langfuse-public-key
          objectType: secret
        - |
          objectName: langfuse-secret-key
          objectType: secret
        - |
          objectName: langfuse-base-url
          objectType: secret

  secretObjects:
    - secretName: financial-secret
      type: Opaque
      data:
        - objectName: openrouter-api-key
          key: openrouter-api-key
        - objectName: news-api-key
          key: news-api-key
        - objectName: langfuse-public-key
          key: langfuse-public-key
        - objectName: langfuse-secret-key
          key: langfuse-secret-key
        - objectName: langfuse-base-url
          key: langfuse-base-url
